config/routes.rb
Howtolist::Application.routes.draw do

  root :to => "listhowtos#index"
  resources :listhowtos do
    resources :steps
  end

end

app/models/listhowto.rb
class Listhowto < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true
  has_many :steps, :dependent => :delete_all
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :listhowto
  attr_accessible :content
  validates :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listhowtos_controller.rb
class ListhowtosController < ApplicationController

  def index
    @how = Listhowto.all
  end

  def new
  @how = Listhowto.new
  end

  def create
  @how = Listhowto.new(params[:listhowto])
  if @how.save
    flash[:notice] = "One howtolist has been created."
    redirect_to @how
  else
    flash[:alert] = "One howtolist has not been created."
    render :action => 'new'
  end
  end

  def show
    @how = Listhowto.find(params[:id])
  end

  def edit
    @how = Listhowto.find(params[:id])
  end

  def update
    @how = Listhowto.new(params[:listhowto])
  if @how.update_attributes(params[:listhowto])
    flash[:notice] = "One howtolist has been updated."
    redirect_to @how
  else
    flash[:alert] = "One howtolist has not been updated."
    render :action => 'edit'
  end
end

  def destroy
  @how = Listhowto.find(params[:id])
  @how.destroy
  flash[:notice] = "One howtolist has been deleted."
  redirect_to listhowtos_path
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :find_listhowto
  before_filter :find_step, :only => [:show, :edit, :update, :destroy]
  def new
  @step = @how.steps.build
  end
  def create
    @step = @how.steps.build(params[:step])
  if @step.save
    flash[:notice] = "Step has been created."
    redirect_to [@how, @step]
  else
    flash[:alert] = "Step has not been created."
    render :action => "new"
  end
  end

  def show
  end
  def edit

  end

  def update
  if @step.update_attributes(params[:step])
    flash[:notice] = "Step has been updated."
    redirect_to [@how, @step]
  else
    flash[:alert] = "Step has not been updated."
    render :action => "edit"
  end
  end

  def destroy
    @step.destroy
  flash[:notice] = "Step has been deleted."
  redirect_to @how
  end

  private

  def find_listhowto
  @how = Listhowto.find(params[:listhowto_id])
  end

  def find_step
  @step = @how.steps.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listhowtos_helper.rb
module ListhowtosHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Howtolist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
<div class='flash' id='<%= key %>'>
<%= value %>
</div>
<% end %>
<%= yield %>

</body>
</html>

app/views/listhowtos/edit.html.erb
<h2>Edit</h2>
<%= form_for(@how) do |f| %>
<%= f.error_messages %>
<p>
<%= f.label :name %><br />
<%= f.text_field :name %>
</p>
<%= f.submit "Update" %>
<% end %>

app/views/listhowtos/index.html.erb
<h1>HowtoLists</h1>
<ul>
<% @how.each do |p| %>
<li><%= link_to p.name, p %></li>
<% end %>
</ul>
<%= link_to "New howtolist" , new_listhowto_path %>

app/views/listhowtos/new.html.erb
<h2>New Howtolist</h2>
<%= form_for(@how) do |f| %>
<p>
<%= f.label :name %><br />
<%= f.text_field :name %>
</p>
<%= f.submit "Create howtolist" %>
<% end %>

app/views/listhowtos/show.html.erb
<h2><%= @how.name %></h2>
<%= link_to "Edit", edit_listhowto_path(@how) %>
<%= link_to "Delete", listhowto_path(@how), :method => "delete", :confirm => "Are you sure you want to delete this howtolist?" %>
<%= link_to "Back", listhowtos_path %>
<%= link_to "New Step", new_listhowto_step_path(@how) %>

<ul id='steps'>
<% @how.steps.each do |step| %>
<li>
<p> Step
  #<%= step.id %> -
<%= link_to step.content, [@how, step] %>
</p>
</li>
<% end %>
</ul>

app/views/steps/edit.html.erb
<h2>Editing a Step in <%= @how.name %></h2>
<%= form_for [@how, @step] do |f| %>
<%= f.error_messages %>
<p>
<%= f.label :content %><br>
<%= f.text_field :content %>
</p>
<%= f.submit "Update" %>
<% end %>

app/views/steps/new.html.erb
<h2>New Step</h2>
<%= form_for [@how, @step] do |f| %>
<%= f.error_messages %>
<p>
<%= f.label :content %><br>
<%= f.text_field :content %>
</p>
<%= f.submit "Create" %>
<% end %>

app/views/steps/show.html.erb
<div id='step'>
<h2><%= @step.content %></h2>
</div>
<%= link_to "Edit", [:edit, @how, @step] %>
<%= link_to "Delete", [@how, @step], :method => :delete,
:confirm => "Are you sure you want to delete this step?" %>
<%= link_to "Back",  @how %>